version: '3.7'
services:
  asterisk:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: "/usr/sbin/asterisk -f -vvvvvvg -c"
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"
    network_mode: "host"
    volumes:
        - "${ASTERISK_CONF:-./conf}:/etc/asterisk"
    restart: "always"
